default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: admin

development:
  <<: *default
  database: ragnarok-db_development

test:
  <<: *default
  database: ragnarok-db_test

production:
  <<: *default
  database: ragnarok-db
  username: admin
  password: <%= ENV['RAGNAROK-DB_DATABASE_PASSWORD'] %>